# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget opencv_cudev opencv_core opencv_cudaarithm opencv_flann opencv_imgproc opencv_ml opencv_objdetect opencv_photo opencv_reg opencv_surface_matching opencv_video opencv_xphoto opencv_bioinspired opencv_cudabgsegm opencv_cudawarping opencv_dpm opencv_face opencv_features2d opencv_fuzzy opencv_imgcodecs opencv_shape opencv_superres opencv_text opencv_calib3d opencv_cudastereo opencv_videostab opencv_aruco)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target opencv_cudev
add_library(opencv_cudev SHARED IMPORTED)

# Create imported target opencv_core
add_library(opencv_core SHARED IMPORTED)

# Create imported target opencv_cudaarithm
add_library(opencv_cudaarithm SHARED IMPORTED)

# Create imported target opencv_flann
add_library(opencv_flann SHARED IMPORTED)

# Create imported target opencv_imgproc
add_library(opencv_imgproc SHARED IMPORTED)

# Create imported target opencv_ml
add_library(opencv_ml SHARED IMPORTED)

# Create imported target opencv_objdetect
add_library(opencv_objdetect SHARED IMPORTED)

# Create imported target opencv_photo
add_library(opencv_photo SHARED IMPORTED)

# Create imported target opencv_reg
add_library(opencv_reg SHARED IMPORTED)

# Create imported target opencv_surface_matching
add_library(opencv_surface_matching SHARED IMPORTED)

# Create imported target opencv_video
add_library(opencv_video SHARED IMPORTED)

# Create imported target opencv_xphoto
add_library(opencv_xphoto SHARED IMPORTED)

# Create imported target opencv_bioinspired
add_library(opencv_bioinspired SHARED IMPORTED)

# Create imported target opencv_cudabgsegm
add_library(opencv_cudabgsegm SHARED IMPORTED)

# Create imported target opencv_cudawarping
add_library(opencv_cudawarping SHARED IMPORTED)

# Create imported target opencv_dpm
add_library(opencv_dpm SHARED IMPORTED)

# Create imported target opencv_face
add_library(opencv_face SHARED IMPORTED)

# Create imported target opencv_features2d
add_library(opencv_features2d SHARED IMPORTED)

# Create imported target opencv_fuzzy
add_library(opencv_fuzzy SHARED IMPORTED)

# Create imported target opencv_imgcodecs
add_library(opencv_imgcodecs SHARED IMPORTED)

# Create imported target opencv_shape
add_library(opencv_shape SHARED IMPORTED)

# Create imported target opencv_superres
add_library(opencv_superres SHARED IMPORTED)

# Create imported target opencv_text
add_library(opencv_text SHARED IMPORTED)

# Create imported target opencv_calib3d
add_library(opencv_calib3d SHARED IMPORTED)

# Create imported target opencv_cudastereo
add_library(opencv_cudastereo SHARED IMPORTED)

# Create imported target opencv_videostab
add_library(opencv_videostab SHARED IMPORTED)

# Create imported target opencv_aruco
add_library(opencv_aruco SHARED IMPORTED)

# Import target "opencv_cudev" for configuration "Release"
set_property(TARGET opencv_cudev APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudev PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_cudev.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_cudev.so.3.2"
  )

# Import target "opencv_core" for configuration "Release"
set_property(TARGET opencv_core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_core PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_core.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_core.so.3.2"
  )

# Import target "opencv_cudaarithm" for configuration "Release"
set_property(TARGET opencv_cudaarithm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudaarithm PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_cudaarithm.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_cudaarithm.so.3.2"
  )

# Import target "opencv_flann" for configuration "Release"
set_property(TARGET opencv_flann APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_flann PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_flann.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_flann.so.3.2"
  )

# Import target "opencv_imgproc" for configuration "Release"
set_property(TARGET opencv_imgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_imgproc PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_imgproc.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_imgproc.so.3.2"
  )

# Import target "opencv_ml" for configuration "Release"
set_property(TARGET opencv_ml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_ml PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_ml.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_ml.so.3.2"
  )

# Import target "opencv_objdetect" for configuration "Release"
set_property(TARGET opencv_objdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_objdetect PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_imgproc;opencv_ml"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_objdetect.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_objdetect.so.3.2"
  )

# Import target "opencv_photo" for configuration "Release"
set_property(TARGET opencv_photo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_photo PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_imgproc"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_photo.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_photo.so.3.2"
  )

# Import target "opencv_reg" for configuration "Release"
set_property(TARGET opencv_reg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_reg PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_imgproc"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_reg.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_reg.so.3.2"
  )

# Import target "opencv_surface_matching" for configuration "Release"
set_property(TARGET opencv_surface_matching APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_surface_matching PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_flann"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_surface_matching.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_surface_matching.so.3.2"
  )

# Import target "opencv_video" for configuration "Release"
set_property(TARGET opencv_video APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_video PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_imgproc"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_video.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_video.so.3.2"
  )

# Import target "opencv_xphoto" for configuration "Release"
set_property(TARGET opencv_xphoto APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_xphoto PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_imgproc;opencv_photo"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_xphoto.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_xphoto.so.3.2"
  )

# Import target "opencv_bioinspired" for configuration "Release"
set_property(TARGET opencv_bioinspired APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_bioinspired PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_bioinspired.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_bioinspired.so.3.2"
  )

# Import target "opencv_cudabgsegm" for configuration "Release"
set_property(TARGET opencv_cudabgsegm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudabgsegm PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_imgproc;opencv_video"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_cudabgsegm.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_cudabgsegm.so.3.2"
  )

# Import target "opencv_cudawarping" for configuration "Release"
set_property(TARGET opencv_cudawarping APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudawarping PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_imgproc"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_cudawarping.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_cudawarping.so.3.2"
  )

# Import target "opencv_dpm" for configuration "Release"
set_property(TARGET opencv_dpm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_dpm PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_imgproc;opencv_ml;opencv_objdetect"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_dpm.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_dpm.so.3.2"
  )

# Import target "opencv_face" for configuration "Release"
set_property(TARGET opencv_face APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_face PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_imgproc;opencv_ml;opencv_objdetect"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_face.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_face.so.3.2"
  )

# Import target "opencv_features2d" for configuration "Release"
set_property(TARGET opencv_features2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_features2d PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_features2d.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_features2d.so.3.2"
  )

# Import target "opencv_fuzzy" for configuration "Release"
set_property(TARGET opencv_fuzzy APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_fuzzy PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_imgproc"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_fuzzy.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_fuzzy.so.3.2"
  )

# Import target "opencv_imgcodecs" for configuration "Release"
set_property(TARGET opencv_imgcodecs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_imgcodecs PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_imgproc"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_imgcodecs.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_imgcodecs.so.3.2"
  )

# Import target "opencv_shape" for configuration "Release"
set_property(TARGET opencv_shape APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_shape PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_imgproc;opencv_video"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_shape.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_shape.so.3.2"
  )

# Import target "opencv_superres" for configuration "Release"
set_property(TARGET opencv_superres APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_superres PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_imgproc;opencv_video;opencv_cudawarping"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_superres.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_superres.so.3.2"
  )

# Import target "opencv_text" for configuration "Release"
set_property(TARGET opencv_text APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_text PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_features2d"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_text.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_text.so.3.2"
  )

# Import target "opencv_calib3d" for configuration "Release"
set_property(TARGET opencv_calib3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_calib3d PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_features2d"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_calib3d.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_calib3d.so.3.2"
  )

# Import target "opencv_cudastereo" for configuration "Release"
set_property(TARGET opencv_cudastereo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudastereo PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_features2d;opencv_calib3d"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_cudastereo.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_cudastereo.so.3.2"
  )

# Import target "opencv_videostab" for configuration "Release"
set_property(TARGET opencv_videostab APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_videostab PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_ml;opencv_photo;opencv_video;opencv_cudawarping;opencv_features2d;opencv_calib3d"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_videostab.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_videostab.so.3.2"
  )

# Import target "opencv_aruco" for configuration "Release"
set_property(TARGET opencv_aruco APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_aruco PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_features2d;opencv_calib3d"
  IMPORTED_LOCATION_RELEASE "/home/user/Downloads/FindCUDA/opencv-3.2.0/release/lib/libopencv_aruco.so.3.2.0"
  IMPORTED_SONAME_RELEASE "libopencv_aruco.so.3.2"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
